#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: PR build

on:
  pull_request:
    branches: [main]

# The build jobs.
jobs:
  build-buildutils:
    uses: ./modules/buildutils/.github/workflows/pr-buildutils.yaml
    
  call-workflow-passing-data:
    uses: example-subflow.yaml
    