#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Maven PR Build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: string
      artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts to download'
        required: true
        type: string

jobs:

  log-unchanged:
    name: Maven is unchanged
    if: ${{ inputs.changed == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The maven module is unchanged"

  build-maven:
    name: Build Maven source code and Docker image
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            modules/maven
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'

      # For any modules that were changed in this PR,
      # download their artifacts from this workflow run.

      - name: Download platform from this workflow
        id: download-platform
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: platform
          path: modules/artifacts

      - name: Download gradle artifacts from this workflow
        id: download-gradle
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts

      # For any modules that weren't changed in this PR,
      # download artifacts from the last successful workflow.

      - name: Download platform from last successful workflow
        if: ${{ steps.download-platform.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: platform
          path: modules/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ inputs.artifact-id }}

      - name: Download gradle artifacts from last successful workflow
        if: ${{ steps.download-gradle.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ inputs.artifact-id }}
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/dev/galasa/**
          key: cache-maven-${{ hashFiles('**/pom.xml') }} 
          restore-keys: |
            cache-maven-
      
      - name: Building Maven source code
        working-directory: modules/maven
        run: |
          mvn -f galasa-maven-plugin/pom.xml deploy -X \
          -Dgpg.skip=true \
          -Dgalasa.source.repo=file:${{ github.workspace }}/modules/artifacts \
          -Dgalasa.central.repo=https://repo.maven.apache.org/maven2/ \
          -Dgalasa.release.repo=file:${{ github.workspace }}/modules/maven/repo \
          --batch-mode --errors --fail-at-end \
          --settings settings.xml

      - name: Upload maven artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven
          path: modules/maven/repo